# This is a basic workflow to help you get started with Actions

name: CI/Python PyLint

# Controls when the action will run. 
on: [push]

  push:
    branches: [ travail ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with: 
          python-version: 3.7
      # Runs a single command using the runners shell
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      #Process of Pylint
      - name: Run Pylint
        run: |
          pylint mon_app.py
